#include "http_server.h"
#include "common.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <pthread.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

struct MetricsServer {
    int port;
    int listen_fd;
    volatile sig_atomic_t running;
    pthread_t thread;
    pthread_mutex_t lock;
    unsigned long total_iterations;
    unsigned long total_alerts;
    time_t last_update;
    int interface_count;
    InterfaceMetrics interfaces[MAX_INTERFACES];
    int rule_count;
    RuleMetrics rules[MAX_RULES];
    AlertHistogram histogram;
};

static void send_response(int client_fd, const char *status,
                          const char *content_type,
                          const char *body)
{
    char header[512];
    int len = snprintf(header, sizeof(header),
                       "HTTP/1.1 %s\r\n"
                       "Content-Type: %s\r\n"
                       "Content-Length: %zu\r\n"
                       "Connection: close\r\n"
                       "\r\n",
                       status, content_type, strlen(body));
    if(len > 0) {
        send(client_fd, header, len, 0);
    }
    send(client_fd, body, strlen(body), 0);
}

#include "http_server.h"
#include "common.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <pthread.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

static void send_metrics(MetricsServer *server, int client_fd)
{
    char body[8192];
    int offset = 0;
    
    // Basic metrics
    offset += snprintf(body + offset, sizeof(body) - offset,
        "# HELP ids_total_iterations Total rate snapshots processed by the analyzer\n"
        "# TYPE ids_total_iterations counter\n"
        "ids_total_iterations %lu\n"
        "# HELP ids_total_alerts_total Total alerts generated by the analyzer\n"
        "# TYPE ids_total_alerts_total counter\n"
        "ids_total_alerts_total %lu\n"
        "# HELP ids_last_update_timestamp_seconds Timestamp of the last metrics update\n"
        "# TYPE ids_last_update_timestamp_seconds gauge\n"
        "ids_last_update_timestamp_seconds %ld\n",
        server->total_iterations, server->total_alerts, (long)server->last_update);
    
    // Per-interface metrics
    for(int i = 0; i < server->interface_count && offset < sizeof(body) - 1000; i++) {
        const InterfaceMetrics *iface = &server->interfaces[i];
        offset += snprintf(body + offset, sizeof(body) - offset,
            "# HELP ids_interface_rx_bytes_per_sec Receive bytes per second for interface %s\n"
            "# TYPE ids_interface_rx_bytes_per_sec gauge\n"
            "ids_interface_rx_bytes_per_sec{interface=\"%s\"} %.2f\n"
            "# HELP ids_interface_tx_bytes_per_sec Transmit bytes per second for interface %s\n"
            "# TYPE ids_interface_tx_bytes_per_sec gauge\n"
            "ids_interface_tx_bytes_per_sec{interface=\"%s\"} %.2f\n"
            "# HELP ids_interface_rx_pkts_per_sec Receive packets per second for interface %s\n"
            "# TYPE ids_interface_rx_pkts_per_sec gauge\n"
            "ids_interface_rx_pkts_per_sec{interface=\"%s\"} %.2f\n"
            "# HELP ids_interface_tx_pkts_per_sec Transmit packets per second for interface %s\n"
            "# TYPE ids_interface_tx_pkts_per_sec gauge\n"
            "ids_interface_tx_pkts_per_sec{interface=\"%s\"} %.2f\n"
            "# HELP ids_interface_rx_errors_per_sec Receive errors per second for interface %s\n"
            "# TYPE ids_interface_rx_errors_per_sec gauge\n"
            "ids_interface_rx_errors_per_sec{interface=\"%s\"} %.2f\n"
            "# HELP ids_interface_tx_errors_per_sec Transmit errors per second for interface %s\n"
            "# TYPE ids_interface_tx_errors_per_sec gauge\n"
            "ids_interface_tx_errors_per_sec{interface=\"%s\"} %.2f\n"
            "# HELP ids_interface_rx_dropped_per_sec Receive dropped packets per second for interface %s\n"
            "# TYPE ids_interface_rx_dropped_per_sec gauge\n"
            "ids_interface_rx_dropped_per_sec{interface=\"%s\"} %.2f\n"
            "# HELP ids_interface_tx_dropped_per_sec Transmit dropped packets per second for interface %s\n"
            "# TYPE ids_interface_tx_dropped_per_sec gauge\n"
            "ids_interface_tx_dropped_per_sec{interface=\"%s\"} %.2f\n",
            iface->interface, iface->interface, iface->rx_bytes_per_sec,
            iface->interface, iface->interface, iface->tx_bytes_per_sec,
            iface->interface, iface->interface, iface->rx_pkts_per_sec,
            iface->interface, iface->interface, iface->tx_pkts_per_sec,
            iface->interface, iface->interface, iface->rx_errors_per_sec,
            iface->interface, iface->interface, iface->tx_errors_per_sec,
            iface->interface, iface->interface, iface->rx_dropped_per_sec,
            iface->interface, iface->interface, iface->tx_dropped_per_sec);
    }
    
    // Per-rule alert counters
    for(int i = 0; i < server->rule_count && offset < sizeof(body) - 500; i++) {
        const RuleMetrics *rule = &server->rules[i];
        offset += snprintf(body + offset, sizeof(body) - offset,
            "# HELP ids_rule_alerts_total Total alerts for rule %s\n"
            "# TYPE ids_rule_alerts_total counter\n"
            "ids_rule_alerts_total{rule=\"%s\"} %lu\n"
            "# HELP ids_rule_last_alert_timestamp_seconds Last alert timestamp for rule %s\n"
            "# TYPE ids_rule_last_alert_timestamp_seconds gauge\n"
            "ids_rule_last_alert_timestamp_seconds{rule=\"%s\"} %ld\n",
            rule->rule_name, rule->rule_name, rule->alert_count,
            rule->rule_name, rule->rule_name, (long)rule->last_alert);
    }
    
    // Alert histogram
    if(server->histogram.total_alerts > 0 && offset < sizeof(body) - 1000) {
        offset += snprintf(body + offset, sizeof(body) - offset,
            "# HELP ids_alert_frequency_histogram Histogram of alert frequencies\n"
            "# TYPE ids_alert_frequency_histogram histogram\n");
        
        double cumulative = 0;
        for(int i = 0; i < HISTOGRAM_BUCKETS; i++) {
            cumulative += server->histogram.buckets[i];
            offset += snprintf(body + offset, sizeof(body) - offset,
                "ids_alert_frequency_histogram_bucket{le=\"%d\"} %.0f\n",
                (i + 1) * 10, cumulative);
        }
        offset += snprintf(body + offset, sizeof(body) - offset,
            "ids_alert_frequency_histogram_count %lu\n"
            "ids_alert_frequency_histogram_sum %lu\n",
            server->histogram.total_alerts, server->histogram.total_alerts);
    }
    
    if(offset >= sizeof(body)) {
        send_response(client_fd, "500 Internal Server Error", "text/plain", "Metrics buffer overflow\n");
        return;
    }
    
    send_response(client_fd, "200 OK", "text/plain; version=0.0.4", body);
}


static void handle_client(MetricsServer *server, int client_fd)
{
    char request[512];
    ssize_t n = recv(client_fd, request, sizeof(request) - 1, 0);
    if(n <= 0) {
        close(client_fd);
        return;
    }
    request[n] = '\0';

    if(strncmp(request, "GET /metrics", 12) == 0) {
        send_metrics(server, client_fd);
    } else if(strncmp(request, "GET /healthz", 11) == 0) {
        send_response(client_fd, "200 OK", "text/plain", "ok\n");
    } else if(strncmp(request, "GET /dashboard", 13) == 0) {
        char *json = metrics_server_create_grafana_dashboard_json(server);
        if(json) {
            send_response(client_fd, "200 OK", "application/json", json);
            free(json);
        } else {
            send_response(client_fd, "500 Internal Server Error", "text/plain", "Failed to generate dashboard\n");
        }
    } else {
        send_response(client_fd, "404 Not Found", "text/plain", "Not Found\n");
    }

    close(client_fd);
}

static void *server_thread(void *arg)
{
    MetricsServer *server = (MetricsServer *)arg;
    struct sockaddr_in addr;

    server->listen_fd = socket(AF_INET, SOCK_STREAM, 0);
    if(server->listen_fd < 0) {
        log_error("Metrics server socket() failed: %s", strerror(errno));
        return NULL;
    }

    int opt = 1;
    setsockopt(server->listen_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(server->port);

    if(bind(server->listen_fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        log_error("Metrics server bind() failed: %s", strerror(errno));
        close(server->listen_fd);
        return NULL;
    }

    if(listen(server->listen_fd, 4) < 0) {
        log_error("Metrics server listen() failed: %s", strerror(errno));
        close(server->listen_fd);
        return NULL;
    }

    log_info("Metrics server listening on port %d", server->port);

    while(server->running) {
        int client_fd = accept(server->listen_fd, NULL, NULL);
        if(client_fd < 0) {
            if(errno == EINTR || errno == EBADF) break;
            continue;
        }
        handle_client(server, client_fd);
    }

    if(server->listen_fd >= 0) {
        close(server->listen_fd);
        server->listen_fd = -1;
    }
    return NULL;
}

MetricsServer *metrics_server_create(int port)
{
    MetricsServer *server = malloc(sizeof(MetricsServer));
    if(!server) return NULL;

    server->port = port;
    server->listen_fd = -1;
    server->running = 1;
    server->total_iterations = 0;
    server->total_alerts = 0;
    server->last_update = time(NULL);
    server->interface_count = 0;
    server->rule_count = 0;
    memset(&server->histogram, 0, sizeof(server->histogram));
    pthread_mutex_init(&server->lock, NULL);

    if(pthread_create(&server->thread, NULL, server_thread, server) != 0) {
        log_error("Failed to start metrics server thread");
        pthread_mutex_destroy(&server->lock);
        free(server);
        return NULL;
    }

    return server;
}

void metrics_server_destroy(MetricsServer *server)
{
    if(!server) return;

    server->running = 0;
    if(server->listen_fd >= 0) {
        close(server->listen_fd);
    }
    pthread_join(server->thread, NULL);
    pthread_mutex_destroy(&server->lock);
    free(server);
}

void metrics_server_update(MetricsServer *server,
                           unsigned long total_iterations,
                           unsigned long total_alerts,
                           time_t last_update)
{
    if(!server) return;

    pthread_mutex_lock(&server->lock);
    server->total_iterations = total_iterations;
    server->total_alerts = total_alerts;
    server->last_update = last_update;
    pthread_mutex_unlock(&server->lock);
}

void metrics_server_update_interfaces(MetricsServer *server,
                                     const RateSnapShot *rates)
{
    if(!server || !rates) return;

    pthread_mutex_lock(&server->lock);
    server->interface_count = rates->count;
    for(int i = 0; i < rates->count && i < MAX_INTERFACES; i++) {
        const RateStats *rate = &rates->interfaces[i];
        InterfaceMetrics *iface = &server->interfaces[i];
        
        strncpy(iface->interface, rate->interface, sizeof(iface->interface) - 1);
        iface->rx_bytes_per_sec = rate->recv_bytes_per_sec;
        iface->tx_bytes_per_sec = rate->tr_bytes_per_sec;
        iface->rx_pkts_per_sec = rate->recv_pkts_per_sec;
        iface->tx_pkts_per_sec = rate->tr_pkts_per_sec;
        iface->rx_errors_per_sec = rate->recv_errors_per_sec;
        iface->tx_errors_per_sec = rate->tr_errors_per_sec;
        iface->rx_dropped_per_sec = rate->recv_dropped_per_sec;
        iface->tx_dropped_per_sec = rate->tr_dropped_per_sec;
    }
    pthread_mutex_unlock(&server->lock);
}

void metrics_server_update_alerts(MetricsServer *server,
                                  const char *rule_name,
                                  time_t alert_time)
{
    if(!server || !rule_name) return;

    pthread_mutex_lock(&server->lock);
    
    // Find or add rule
    int rule_idx = -1;
    for(int i = 0; i < server->rule_count; i++) {
        if(strcmp(server->rules[i].rule_name, rule_name) == 0) {
            rule_idx = i;
            break;
        }
    }
    
    if(rule_idx == -1 && server->rule_count < MAX_RULES) {
        rule_idx = server->rule_count++;
        strncpy(server->rules[rule_idx].rule_name, rule_name, 
                sizeof(server->rules[rule_idx].rule_name) - 1);
        server->rules[rule_idx].alert_count = 0;
    }
    
    if(rule_idx >= 0) {
        server->rules[rule_idx].alert_count++;
        server->rules[rule_idx].last_alert = alert_time;
        
        // Update histogram (simple bucket based on alert count)
        int bucket = server->rules[rule_idx].alert_count / 10;
        if(bucket < HISTOGRAM_BUCKETS) {
            server->histogram.buckets[bucket]++;
        }
        server->histogram.total_alerts++;
    }
    
    pthread_mutex_unlock(&server->lock);
}

char *metrics_server_create_grafana_dashboard_json(MetricsServer *server)
{
    if(!server) return NULL;

    // Allocate a large buffer for the JSON
    char *json = calloc(1, 16384);
    if(!json) return NULL;

    int offset = 0;
    offset += snprintf(json + offset, 16384 - offset,
        "{\n"
        "  \"dashboard\": {\n"
        "    \"id\": null,\n"
        "    \"title\": \"Network IDS Metrics\",\n"
        "    \"tags\": [\"ids\", \"network\", \"monitoring\"],\n"
        "    \"timezone\": \"browser\",\n"
        "    \"panels\": [\n");

    // Panel 1: Total Iterations and Alerts
    offset += snprintf(json + offset, 16384 - offset,
        "      {\n"
        "        \"id\": 1,\n"
        "        \"title\": \"IDS Overview\",\n"
        "        \"type\": \"stat\",\n"
        "        \"targets\": [\n"
        "          {\n"
        "            \"expr\": \"ids_total_iterations\",\n"
        "            \"legendFormat\": \"Total Iterations\"\n"
        "          },\n"
        "          {\n"
        "            \"expr\": \"ids_total_alerts_total\",\n"
        "            \"legendFormat\": \"Total Alerts\"\n"
        "          }\n"
        "        ],\n"
        "        \"gridPos\": {\"h\": 8, \"w\": 12, \"x\": 0, \"y\": 0}\n"
        "      },\n");

    // Panel 2: Interface Traffic
    offset += snprintf(json + offset, 16384 - offset,
        "      {\n"
        "        \"id\": 2,\n"
        "        \"title\": \"Interface Traffic (Bytes/sec)\",\n"
        "        \"type\": \"graph\",\n"
        "        \"targets\": [\n"
        "          {\n"
        "            \"expr\": \"ids_interface_rx_bytes_per_sec\",\n"
        "            \"legendFormat\": \"{{interface}} RX\"\n"
        "          },\n"
        "          {\n"
        "            \"expr\": \"ids_interface_tx_bytes_per_sec\",\n"
        "            \"legendFormat\": \"{{interface}} TX\"\n"
        "          }\n"
        "        ],\n"
        "        \"gridPos\": {\"h\": 8, \"w\": 12, \"x\": 12, \"y\": 0}\n"
        "      },\n");

    // Panel 3: Packet Rates
    offset += snprintf(json + offset, 16384 - offset,
        "      {\n"
        "        \"id\": 3,\n"
        "        \"title\": \"Packet Rates (Packets/sec)\",\n"
        "        \"type\": \"graph\",\n"
        "        \"targets\": [\n"
        "          {\n"
        "            \"expr\": \"ids_interface_rx_pkts_per_sec\",\n"
        "            \"legendFormat\": \"{{interface}} RX\"\n"
        "          },\n"
        "          {\n"
        "            \"expr\": \"ids_interface_tx_pkts_per_sec\",\n"
        "            \"legendFormat\": \"{{interface}} TX\"\n"
        "          }\n"
        "        ],\n"
        "        \"gridPos\": {\"h\": 8, \"w\": 12, \"x\": 0, \"y\": 8}\n"
        "      },\n");

    // Panel 4: Error Rates
    offset += snprintf(json + offset, 16384 - offset,
        "      {\n"
        "        \"id\": 4,\n"
        "        \"title\": \"Error Rates\",\n"
        "        \"type\": \"graph\",\n"
        "        \"targets\": [\n"
        "          {\n"
        "            \"expr\": \"ids_interface_rx_errors_per_sec\",\n"
        "            \"legendFormat\": \"{{interface}} RX Errors\"\n"
        "          },\n"
        "          {\n"
        "            \"expr\": \"ids_interface_tx_errors_per_sec\",\n"
        "            \"legendFormat\": \"{{interface}} TX Errors\"\n"
        "          }\n"
        "        ],\n"
        "        \"gridPos\": {\"h\": 8, \"w\": 12, \"x\": 12, \"y\": 8}\n"
        "      },\n");

    // Panel 5: Rule Alerts
    offset += snprintf(json + offset, 16384 - offset,
        "      {\n"
        "        \"id\": 5,\n"
        "        \"title\": \"Rule Alert Counts\",\n"
        "        \"type\": \"bargauge\",\n"
        "        \"targets\": [\n"
        "          {\n"
        "            \"expr\": \"ids_rule_alerts_total\",\n"
        "            \"legendFormat\": \"{{rule}}\"\n"
        "          }\n"
        "        ],\n"
        "        \"gridPos\": {\"h\": 8, \"w\": 12, \"x\": 0, \"y\": 16}\n"
        "      },\n");

    // Panel 6: Alert Frequency Histogram
    offset += snprintf(json + offset, 16384 - offset,
        "      {\n"
        "        \"id\": 6,\n"
        "        \"title\": \"Alert Frequency Distribution\",\n"
        "        \"type\": \"heatmap\",\n"
        "        \"targets\": [\n"
        "          {\n"
        "            \"expr\": \"increase(ids_alert_frequency_histogram_bucket[5m])\",\n"
        "            \"legendFormat\": \"{{le}}\"\n"
        "          }\n"
        "        ],\n"
        "        \"gridPos\": {\"h\": 8, \"w\": 12, \"x\": 12, \"y\": 16}\n"
        "      }\n"
        "    ],\n"
        "    \"time\": {\n"
        "      \"from\": \"now-1h\",\n"
        "      \"to\": \"now\"\n"
        "    },\n"
        "    \"timepicker\": {},\n"
        "    \"templating\": {\n"
        "      \"list\": []\n"
        "    },\n"
        "    \"annotations\": {\n"
        "      \"list\": []\n"
        "    },\n"
        "    \"refresh\": \"5s\",\n"
        "    \"schemaVersion\": 27,\n"
        "    \"version\": 0,\n"
        "    \"links\": []\n"
        "  }\n"
        "}\n");

    return json;
}
