#include "http_server.h"
#include "common.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <pthread.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

struct MetricsServer {
    int port;
    int listen_fd;
    volatile sig_atomic_t running;
    pthread_t thread;
    pthread_mutex_t lock;
    unsigned long total_iterations;
    unsigned long total_alerts;
    time_t last_update;
};

static void send_response(int client_fd, const char *status,
                          const char *content_type,
                          const char *body)
{
    char header[512];
    int len = snprintf(header, sizeof(header),
                       "HTTP/1.1 %s\r\n"
                       "Content-Type: %s\r\n"
                       "Content-Length: %zu\r\n"
                       "Connection: close\r\n"
                       "\r\n",
                       status, content_type, strlen(body));
    if(len > 0) {
        send(client_fd, header, len, 0);
    }
    send(client_fd, body, strlen(body), 0);
}

static void send_metrics(MetricsServer *server, int client_fd)
{
    char body[1024];
    unsigned long iterations;
    unsigned long alerts;
    time_t last_update;

    pthread_mutex_lock(&server->lock);
    iterations = server->total_iterations;
    alerts = server->total_alerts;
    last_update = server->last_update;
    pthread_mutex_unlock(&server->lock);

    int len = snprintf(body, sizeof(body),
        "# HELP ids_total_iterations Total rate snapshots processed by the analyzer\n"
        "# TYPE ids_total_iterations counter\n"
        "ids_total_iterations %lu\n"
        "# HELP ids_total_alerts_total Total alerts generated by the analyzer\n"
        "# TYPE ids_total_alerts_total counter\n"
        "ids_total_alerts_total %lu\n"
        "# HELP ids_last_update_timestamp_seconds Timestamp of the last metrics update\n"
        "# TYPE ids_last_update_timestamp_seconds gauge\n"
        "ids_last_update_timestamp_seconds %ld\n",
        iterations, alerts, (long)last_update);

    if(len < 0 || (size_t)len >= sizeof(body)) {
        send_response(client_fd, "500 Internal Server Error", "text/plain", "Metrics generation failed\n");
        return;
    }

    send_response(client_fd, "200 OK", "text/plain; version=0.0.4", body);
}

static void handle_client(MetricsServer *server, int client_fd)
{
    char request[512];
    ssize_t n = recv(client_fd, request, sizeof(request) - 1, 0);
    if(n <= 0) {
        close(client_fd);
        return;
    }
    request[n] = '\0';

    if(strncmp(request, "GET /metrics", 12) == 0) {
        send_metrics(server, client_fd);
    } else if(strncmp(request, "GET /healthz", 11) == 0) {
        send_response(client_fd, "200 OK", "text/plain", "ok\n");
    } else {
        send_response(client_fd, "404 Not Found", "text/plain", "Not Found\n");
    }

    close(client_fd);
}

static void *server_thread(void *arg)
{
    MetricsServer *server = (MetricsServer *)arg;
    struct sockaddr_in addr;

    server->listen_fd = socket(AF_INET, SOCK_STREAM, 0);
    if(server->listen_fd < 0) {
        log_error("Metrics server socket() failed: %s", strerror(errno));
        return NULL;
    }

    int opt = 1;
    setsockopt(server->listen_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(server->port);

    if(bind(server->listen_fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        log_error("Metrics server bind() failed: %s", strerror(errno));
        close(server->listen_fd);
        return NULL;
    }

    if(listen(server->listen_fd, 4) < 0) {
        log_error("Metrics server listen() failed: %s", strerror(errno));
        close(server->listen_fd);
        return NULL;
    }

    log_info("Metrics server listening on port %d", server->port);

    while(server->running) {
        int client_fd = accept(server->listen_fd, NULL, NULL);
        if(client_fd < 0) {
            if(errno == EINTR || errno == EBADF) break;
            continue;
        }
        handle_client(server, client_fd);
    }

    if(server->listen_fd >= 0) {
        close(server->listen_fd);
        server->listen_fd = -1;
    }
    return NULL;
}

MetricsServer *metrics_server_create(int port)
{
    MetricsServer *server = malloc(sizeof(MetricsServer));
    if(!server) return NULL;

    server->port = port;
    server->listen_fd = -1;
    server->running = 1;
    server->total_iterations = 0;
    server->total_alerts = 0;
    server->last_update = time(NULL);
    pthread_mutex_init(&server->lock, NULL);

    if(pthread_create(&server->thread, NULL, server_thread, server) != 0) {
        log_error("Failed to start metrics server thread");
        pthread_mutex_destroy(&server->lock);
        free(server);
        return NULL;
    }

    return server;
}

void metrics_server_destroy(MetricsServer *server)
{
    if(!server) return;

    server->running = 0;
    if(server->listen_fd >= 0) {
        close(server->listen_fd);
    }
    pthread_join(server->thread, NULL);
    pthread_mutex_destroy(&server->lock);
    free(server);
}

void metrics_server_update(MetricsServer *server,
                           unsigned long total_iterations,
                           unsigned long total_alerts,
                           time_t last_update)
{
    if(!server) return;

    pthread_mutex_lock(&server->lock);
    server->total_iterations = total_iterations;
    server->total_alerts = total_alerts;
    server->last_update = last_update;
    pthread_mutex_unlock(&server->lock);
}
